### ISSUE TITLE
Fix smartctl use without sudo

### ISSUE THREAD

**Issue by il-palmi** [WEEE-Open/pesto#119]
Add user to `disk` group to avoid use of `sudo` in basilico.py to scan disks with smartctl.
Use install.sh and uninstall.sh to automatically add and remove user to the group, ask gently with a prompt please :)

**Comment by il-palmi** [comment]
Apparently, adding the user to disk group is not sufficient to use smartctl without root privileges. Looking for an alternative.

**Comment by lvps** [comment]
Resolved by the sudo password prompt + other stuff
