### ISSUE TITLE
UEFI disks are not supported

### ISSUE THREAD

**Issue by Al3cr1s** [WEEE-Open/pesto#121]
The software only supports bios disks and not uefi, #FIXME line 629 in basilico.py, if it is a uefi disk it should be resizing partition 3 but is resizing partition 1.

**Comment by lvps** [comment]
Maybe it should detect the partition type and resize the the first "Linux filesystem" one it finds, or the last one, or skip the "EFI Sytem" one (or the same thing using UUIDs).
All the data we could ever desire can be obtained with `lsblk -J -o PATH,FSTYPE,PARTFLAGS,PARTLABEL,PARTN,PARTTYPE,PARTTYPENAME,PTTYPE` once the image has been written, or with `fdisk -l asd.img` before writing anything, which is harder to parse tough

**Comment by parmigggiana** [comment]
The last partition created by the latest release are still not resized

**Comment by lvps** [comment]
Fixed in https://github.com/WEEE-Open/pesto/commit/24f2e0b85a7875fb2ea2d6a25c517257eec68276 (possibly)
