### ISSUE TITLE
Add progress bar to badblocks

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/pesto#16]
It would be a very nice, if not needed, improvement.   
Suggestions:  
- use `tqdm` in Python
- pass the badblocks progress bar through Python, if it has one

**Comment by lvps** [comment]
The problem is now to read the badblocks output and pass the percentage to the client, which already has a progress bar ready

**Comment by ThePalm99** [comment]
It would be useful to show in the GUI both the number of completed badblocks operations and the percentage of the current operation

[ID] [PROCESS] [DRIVE] [STATUS] [1/3] [===96%===]

**Comment by ThePalm99** [comment]
It would be useful to show in the GUI both the number of completed badblocks operations and the percentage of the current operation

[ID] [PROCESS] [DRIVE] [STATUS] [1/3] [===96%===]

**Comment by lvps** [comment]
Done in https://github.com/WEEE-Open/pesto/commit/62a49bd4402e9a1e75e921605f8591183ed1c030
