### ISSUE TITLE
Auto-terminate server if in local mode

### ISSUE THREAD

**Issue by ThePalm99** [WEEE-Open/pesto#22]
Will be handy if the server could know that is running in a local configuration and, when the connection is closed, it must shutdown itself to avoid that the socket in use remain occupied in case of a client crash.

To make it, the client can run the process with the command:  
```
python pesto_server.py --local
```
when in local mode, and in remote mode:
```
python pesto_server.py
```

**Comment by lvps** [comment]
@ThePalm99 Or set an env var like LOCAL_MODE

**Comment by lvps** [comment]
Done in #46
