### ISSUE TITLE
Queue is not queued

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/pesto#25]
Threads wait on a lock. But they don't wait in order! If 2 threads are queued, when the lock is released, which one will go is random and depends on the scheduler!

**Comment by e-caste** [comment]
@lvps This is usually solved with a counter and an if.

Example:

acquire lock
cnt += 1
if cnt == my_id:
    proceed

**Comment by lvps** [comment]
@e-caste Thanks man asd

**Comment by e-caste** [comment]
@lvps No problem. Although keep in mind that these are UNIX primitives I have studied in C, there may be some more high level primitive available in Python, IIRC Queues are natively implemented for example
