### ISSUE TITLE
Add drop down menu for queue management

### ISSUE THREAD

**Issue by ThePalm99** [WEEE-Open/pesto#9]
Right click to show drop down menu with:
- stop
- pause
- resume
- remove

**Comment by lvps** [comment]
@ThePalm99 How about square buttons with a symbol, like media players?
▶️ ⏸ ❎ and resume is the same as ▶️

**Comment by lvps** [comment]
@ThePalm99 Also, pause/resume may be hard to implement in turbofresa... but a cancel (⏹) button would be good
